### PR TITLE
Update for ipywidgets 7.0 and JupyterLab 0.28

### LINKED ISSUE #15: compatibility with ipywidgets-7.0.0 and later ?
With latest ipywidgets-7.0.0b6 , the example https://github.com/matplotlib/jupyter-matplotlib/blob/master/examples/ipympl.ipynb runs srtangely on classic notebook (not really usable).

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #15. 

- Removed export button and fixed the handling of interactivity toggling.
- Fixed the download image behavior since Chrome no longer supports data urls for `window.open`.

mpl-widget

### CODE REVIEW

**Comment by blink1073** [comment]
@tacaswell @SylvainCorlay, I had one bug that I can't figure out.  I sometimes get the following error that is cleared by restarting the kernel:

image

**Comment by blink1073** [comment]
cc @jasongrout

**Comment by blink1073** [comment]
Note that the video above shows it creating a new window to download.  I changed it so that it automatically downloads '<figure_title>.png` without navigating away from the page.

**Comment by blink1073** [comment]
Note that the following also works (should this close #9)?:

```python
%matplotlib ipympl
import matplotlib.pyplot as plt

plt.plot([0, 1, 2, 2])
plt.show()
```

**Comment by blink1073** [comment]
Found the source of the usage error:

https://github.com/ipython/ipython/blob/dfb458636b247a78f4a57206128caffd97035ea5/IPython/core/pylabtools.py#L27

Ensured that we always get "ipympl" in 676ea16.

**Comment by blink1073** [comment]
Ah, the problem is that the addition of `widget` in `IPython.core.pylabtools` needed a corresponding addition to https://github.com/ipython/ipykernel/blob/71c44fe80e79126de4f27e6713fda1d274132d77/ipykernel/eventloops.py#L45.

**Comment by blink1073** [comment]
PR: https://github.com/ipython/ipykernel/pull/275

**Comment by SylvainCorlay** [comment]
Goog catch for the IPython backend name!

**Comment by blink1073** [comment]
Sweet!  Can you add me to the PyPI maintainers?

**Comment by SylvainCorlay** [comment]
Done!

**Pull request merged**
