### PR TITLE
Use binary buffers

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@martinRenou is this a replacement for #91 ?

**Comment by martinRenou** [comment]
Yes it is, feel free to close #91 if you prefer this implementation. I honestly preferred the implementation in #91 but could not make it work properly (it doesn't redraw on events). 

While this PR works like a charm.

**Comment by SylvainCorlay** [comment]
Could we merge this and rebase the other one on the top of it?

**Comment by martinRenou** [comment]
As you wish, but the other one will stay WIP

**Comment by SylvainCorlay** [comment]
OK, let's go with this.

**Pull request merged**
