### PR TITLE
Resize handle

### LINKED ISSUE #44: Resize handle feature
I am really missing the ability to resize the plot with the mouse like in the picture bellow with the grey bottom right corner arrow.

### PR DESCRIPTION
**Pull request by martinRenou**
Allow resizing the plot with the mouse, this will fix #44 

cc. @kboone 

resize

### CODE REVIEW

**Comment by martinRenou** [comment]
TODO:
- [ ] Get rid of the flickering
- [ ] Debounce the `resize` calls (do nothing if there is already a resizing happening, wait until it's finished before replaying a resize).
- [ ] Improve resize handle design?

**Comment by martinRenou** [comment]
resize

**Comment by jakirkham** [comment]
Thanks so much Martin for doing this work! 😄

**Comment by kboone** [comment]
Thanks, this looks great! I made a couple of tweaks in #183 that I think improve usability a bit when rendering is slower.

**Pull request merged**
