### PR TITLE
[WIP] Initial take on a lab plugin.

### PR DESCRIPTION
**Pull request by jasongrout**
Still have lots of errors, but we can start working on them now
that the javascript is loading. This is definitely still a work in progress.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
woot !

**Comment by stonebig** [comment]
hi, is it suppose to work with latest jupyterlab/ipywidgets ? I don't succeed but I may have done something wring

**Comment by blink1073** [comment]
No, this was using an older iteration of the JupyterLab extension system.

**Comment by stonebig** [comment]
any progress ?

**Comment by blink1073** [comment]
Unfortunately we didn't get a chance to work on it while at JupyterCon.

**Comment by blink1073** [comment]
Closing in favor of #21.

**Pull request closed without merging**
